.pc
.TH SRBPP.JSON 5 "2021-03-21" "SRB++" "Speedrunbot++ Configuration File"
.SH NAME
srbpp.json \- speedrunbot++ configuration file
.SH SYNOPSIS
.PP
data/srbpp.json
.SH DESCRIPTION
.PP
The
data/srbpp.json
file contains the configuration options for the speedrunbot++ discord bot.
.PP
The configuration file is a simple JSON file. Nobody besides the bots host or
other trusted individuals should have access to this file as it both contains
sensitive information, and can be destructive if the wrong user gets their hands
on it.
.SH OPTIONS
.PP
The following keys can be added to the JSON configuration file:
.PP
\fI"token": ""\fR
.RS 4
A string containing the bots token. This token can be obtained from
\fIhttps://discord.com/developers/applications/<application_id>/bot\fR. Be
careful with who you share this token with, as anyone with the token can run
code using your bot.
.RE
.PP
\fI"botmasters": []\fR
.RS 4
An array of discord user IDs in the form of integers. The users identified by
the given user IDs will be classified as \fBbotmasters\fR. A botmaster is a user
with increased priveleges. This includes being able to load and unload cogs,
pull code from git, etc. It is advised that you do not let anyone put their ID
here.
.RE
.SH EXAMPLE
.sp
.if n \{\
.RS 4
.\}
.nf
{
	"token": "hunter2",
	"botmasters": [
		280428276810383370
	]
}
.fi
