.pc
.TH VERIFIED 1 "2021-03-21" "1.0.0" "Speedrunbot++ Commands Manual"
.SH NAME
verified \- get the number of runs verified and rejected by a user
.SH SYNOPSIS
.B verified
.RI [\| "USER" \|]
.SH DESCRIPTION
.B verified
is a commandline utility to get the number of runs verified or rejected by a
\fIspeedrun.com\fR user. The data comes from the \fIspeedrun.com\fR API, and as
such requires a working internet connection. The program takes a single
\fBUSER\fR as an argument, and an error is displayed if \fBUSER\fR isn't found.
.SH EXAMPLES
.TP \w'verified\ 'u
.BI verified \ AnInternetTroll
Display the number of runs verified and rejected by
\fIhttps://www.speedrun.com/user/AnInternetTroll\fR.
.SH "EXIT STATUS"
.TP
.B 0
Successful program execution.
.TP
.B 1
User given by \fBargv[1]\fR not found.
.SH AUTHORS
.PP
Written by Mango Man.